#basic settings
language: node_js
node_js:
  - "4.4"
env:
 - CXX=g++-4.8
addons:
 apt:
  sources:
   - ubuntu-toolchain-r-test
  packages:
   - g++-4.8

#test script options
before_script:
  # - npm install -g gulp
script: gulp eslint

#notify CI results
notifications:
  email: false
